#Bloque raiz de configuracion de Spring Boot.
spring:

  #Se usa H2 en memoria para que funcione en Render.
  #datasource:
    #url: jdbc:h2:mem:testdb
    #username: sa
    #password:
    #driver-class-name: org.h2.Driver

  datasource:
      url: jdbc:mysql://localhost:3306/device?useSSL=false&serverTimezone=UTC
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver

  #Configuracion de JPA/Hibernate (capa de persistencia).
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  #Habilita la consola web de H2 (opcional).
  h2:
    console:
      enabled: true

  devtools:
    restart:
      enabled: true

#Configuracion del servidor embebido (Tomcat).
#Render usa puertos dinamicos.
server:
  port: ${PORT:8080}

# Versión de la aplicacion
app:
  version: ${APP_VERSION:dev-local}